### ISSUE TITLE
About Section

### ISSUE THREAD

**Issue by fostergn** [jerrywalters/rewards-marketplace#6]
## Description
Create some sort of button that shows an about section that describes the tool and how to use it.

### Todo List
- [ ] Design button or icon for about
- [ ] Style button or icon
- [ ] Create modal for about
- [ ] Add UI to state for modal close and open

**Comment by jerrywalters** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;72c4EVL6&#x2F;8-about-section"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> About Section</a>
