### ISSUE TITLE
Reward Money Spent

### ISSUE THREAD

**Issue by fostergn** [jerrywalters/rewards-marketplace#8]
## Description
Have indicator of monthly money spent out of monthly allowance

### Todo List
- [ ] Design icon or system to show money spent
- [ ] Add money spent to state
- [ ] Have slider value relate to money spent
